{% set name = "unlzw3" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unlzw3-{{ version }}.tar.gz
  sha256: d037a9b6823d1a455d6de1e0258af8c0f5dbf40aba3b19cc514448e78da77062

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - unlzw3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scivision/unlzw3
  summary: Pure Python decompression module for .Z files compressed using Unix compress utility
  license: Zlib
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marie59
