{% set name = "unlzw3" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unlzw3-{{ version }}.tar.gz
  sha256: ede5d928c792fff9da406f20334f9739693327f448f383ae1df1774627197bbb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - unlzw3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scivision/unlzw3
  summary: Pure Python decompression module for .Z files compressed using Unix compress utility
  license: Zlib
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marie59
